:development:
  :adapter:  mysql
  :host:     everest
  :username: food_user
  :password: fud_usr
  :database: food_dev

  #:adapter:  sqlite
  #:database: development.db

:test:
  :adapter:  mysql
  :host:     everest
  :username: food_user
  :password: fud_usr
  :database: food_test

:production:
  :adapter:  mysql
  :host:     everest
  :username: food_user
  :password: fud_usr
  :database: food_prod
