require 'rubygems'
require 'rake'

def __DIR__
  File.expand_path(File.dirname(__FILE__))
end

import File.join(__DIR__, '..', 'db/Rakefile')

namespace :test do
  namespace :www do

    desc "Test user related stuff."
    task :user => ['test:db:setup'] do
      cd __DIR__ do
        sh "spec --format specdoc -c spec/user_spec.rb"
      end
    end
  end

  desc "Run all website tests."
  task :www => ['test:db:setup', 'www:user']
end

namespace :run do

  desc "Run the web server."
  task :www do
    #sh "ruby -C www init.rb"
    cd __DIR__ do
      sh "shotgun config.ru -p 4567"
    end
  end
end
